# -*- coding: utf-8 -*-
"""serie temp pi eurocycle.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nvG0vIuS8Lk_9V9NELU9scyU8sVx3gEe
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import statsmodels.api as sm
from statsmodels.graphics.tsaplots import plot_acf
from statsmodels.graphics.tsaplots import plot_pacf
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.ar_model import AR
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.stats.diagnostic import acorr_ljungbox
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error, mean_squared_log_error

df= pd.read_csv('EUROCYCLES_stock bourse.xls',index_col=0, parse_dates=True)
df

df.index = pd.to_datetime(df.index, format='%d/%m/%Y')
df = df.sort_values('Date', ascending=True)
df = df[(df.index >= '2015-01-01') & (df.index <= '2024-12-31')]
df

df.isnull().sum()

df[df.duplicated(keep=False)]

df.info()

plt.figure(figsize=(12, 6))
plt.plot(df['Cloture'],linewidth = 1)
plt.xlabel('Date')
plt.ylabel('cloture')
plt.show()

decomposition = seasonal_decompose(df['Cloture'], model="multiplicative",period=252)

# Extraction des composantes
trend = decomposition.trend
seasonal = decomposition.seasonal
residual = decomposition.resid

plt.figure(figsize=(10, 8))

plt.subplot(411)
plt.plot(df['Cloture'], label='Originale')
plt.legend(loc='upper left')

plt.subplot(412)
plt.plot(trend, label='Tendance')
plt.legend(loc='upper left')

plt.subplot(413)
plt.plot(seasonal, label='Saisonnalité')
plt.legend(loc='upper left')

plt.subplot(414)
plt.plot(residual, label='Résidu')
plt.legend(loc='upper left')

plt.tight_layout()
plt.show()

result = adfuller(df['Cloture'], autolag='AIC')

# Affiche la statistique du test et la valeur p
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])

# Interpréter les résultats
if result[1] < 0.05:
    print('La série est stationnaire.')
else:
    print('La série est non-stationnaire.')

ts_diff =df['Cloture'].diff()
ts_diff =df['Cloture'].diff().dropna()
ts_diff.head()

result = adfuller(ts_diff, autolag='AIC')

# Affiche la statistique du test et la valeur p
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])

# Interpréter les résultats
if result[1] < 0.05:
    print('La série est stationnaire.')
else:
    print('La série est non-stationnaire.')

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

# Tracé de la série initiale et différenciée
df['Cloture'].plot(title="Série originale",color="tab:blue", ax=ax1)

ts_diff.plot(title="Série différenciée d'ordre 1", color="tab:red", ax=ax2)

plt.show()

fig, (ax1, ax2)= plt.subplots(1,2, figsize=(12, 4))

plot_acf(ts_diff,lags=50, ax=ax1)
ax1.set_title('ACF')

plot_pacf(ts_diff,lags=50, ax=ax2)
ax2.set_title('PACF')

plt.show()

size= int(len(df)*0.8)
train_ts = df['Cloture'].dropna().iloc[:size]
test_ts  = df['Cloture'].dropna().iloc[size:]

from pmdarima import auto_arima

model = auto_arima(train_ts, start_p=0,d=1,start_q=0,
         max_p=5,max_d=5,max_q=5)

print(model.summary())

model = ARIMA(train_ts, order = (1,1,0))
model_fit = model.fit()
print(model_fit.summary())

history = list(train_ts)
predictions = []

for i in range(len(test_ts)):
    model_temp = ARIMA(history, order=(2,1,1)).fit()
    yhat = model_temp.forecast(steps=1)[0]
    predictions.append(yhat)
    history.append(test_ts.iloc[i])

prediction_walk = pd.Series(predictions, index=test_ts.index)

# Graphique
plt.figure(figsize=(14, 6))
plt.plot(train_ts.index, train_ts, label='Train data', color='steelblue', linewidth=0.8)
plt.plot(test_ts.index, test_ts, label='Test data (réel)', color='orange', linewidth=1.2)
plt.plot(prediction_walk.index, prediction_walk, label='Prédiction ARIMA(2,1,1) one-step',
         color='green', linewidth=1.2, linestyle='--')
plt.title('Prédiction one-step-ahead - ARIMA(2,1,1)', fontsize=14)
plt.xlabel('Date')
plt.ylabel('Prix de clôture (TND)')
plt.legend()
plt.tight_layout()
plt.show()

# Métriques
rmse = np.sqrt(mean_squared_error(test_ts, prediction_walk))
mae  = mean_absolute_error(test_ts, prediction_walk)
mape = np.mean(np.abs((test_ts.values - prediction_walk.values) / test_ts.values)) * 100
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")
print(f"MAPE : {mape:.2f}%")
history = list(train_ts)
predictions = []

ts_diff_S = ts_diff.diff(5).dropna()

result = adfuller(ts_diff_S, autolag='AIC')

# Affiche la statistique du test et la valeur p
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])

# Interpréter les résultats
if result[1] < 0.05:
    print('La série est stationnaire.')
else:
    print('La série est non-stationnaire.')

model = auto_arima(train_ts,
        start_p=3,d=1,start_q=0,
         max_p=3,max_d=1,max_q=0,
        start_P=0,D=1, start_Q=0,
        max_P=5,max_D=5,max_Q=5,
        m=5,seasonal=True)
print(model.summary())

from statsmodels.tsa.statespace.sarimax import SARIMAX

history_s = list(train_ts.values)
predictions_sarima = []
model_fit = None
REFIT_EVERY = 10

for i in range(len(test_ts)):

    if i % REFIT_EVERY == 0:
        model_fit = SARIMAX(history_s,
                            order=(1, 1, 0),
                            seasonal_order=(5, 1, 0, 5)).fit(
                                disp=False,
                                method='powell',
                                maxiter=50
                            )
    else:

        model_fit = model_fit.append([test_ts.iloc[i-1]], refit=False)

    yhat_s = model_fit.forecast(steps=1)[0]
    predictions_sarima.append(yhat_s)
    history_s.append(test_ts.iloc[i])

pred_sarima_walk = pd.Series(predictions_sarima, index=test_ts.index)


# GRAPHIQUE

plt.figure(figsize=(14, 6))
plt.plot(train_ts.index, train_ts, label='Train data', color='steelblue', linewidth=0.8)
plt.plot(test_ts.index, test_ts, label='Test data (réel)', color='orange', linewidth=1.2)
plt.plot(pred_sarima_walk.index, pred_sarima_walk,
         label='Prédiction SARIMA(1,1,0)(5,1,0,5)',
         color='green', linewidth=1.2, linestyle='--')
plt.title('Prédiction one-step-ahead - SARIMA(1,1,0)(5,1,0,5)', fontsize=14)
plt.xlabel('Date')
plt.ylabel('Prix de clôture (TND)')
plt.legend()
plt.tight_layout()
plt.show()


# MÉTRIQUES

rmse_s = np.sqrt(mean_squared_error(test_ts, pred_sarima_walk))
mae_s  = mean_absolute_error(test_ts, pred_sarima_walk)
mape_s = np.mean(np.abs((test_ts.values - pred_sarima_walk.values) / test_ts.values)) * 100

print("=" * 45)
print(f"{'Modèle':<25} {'RMSE':>6} {'MAE':>6} {'MAPE':>7}")
print("=" * 45)
print(f"{'ARIMA(2,1,1)':<25} {0.2851:>6.4f} {0.1692:>6.4f} {1.11:>6.2f}%")
print(f"{'SARIMA(1,1,0)(5,1,0,5)':<25} {rmse_s:>6.4f} {mae_s:>6.4f} {mape_s:>6.2f}%")
print("=" * 45)

