# -*- coding: utf-8 -*-
"""serie temp plast.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wl_6Qbir5bcXnX-70n_c3XL5ESerAFcz
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import statsmodels.api as sm
from statsmodels.graphics.tsaplots import plot_acf
from statsmodels.graphics.tsaplots import plot_pacf
from statsmodels.tsa.stattools import adfuller
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.ar_model import AR
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.stats.diagnostic import acorr_ljungbox
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, median_absolute_error, mean_squared_log_error

df= pd.read_csv('PLAST_stock bourse.xls',index_col=0, parse_dates=True)
df

df.index = pd.to_datetime(df.index, format='%d/%m/%Y')
df = df.sort_values('Date', ascending=True)
df = df[(df.index >= '2015-01-01') & (df.index <= '2024-12-31')]
df

df.isnull().sum()

df[df.duplicated(keep=False)]

df = df[~df.duplicated()]
df

df.info()

# Nettoyage de la colonne Cloture
df['Cloture'] = df['Cloture'].astype(str).str.replace(',', '.').str.replace(' ', '').str.strip()
df['Cloture'] = pd.to_numeric(df['Cloture'], errors='coerce')
df = df[~df.index.duplicated(keep='first')]
df = df.sort_index()
df['Cloture'] = df['Cloture'].interpolate(method='linear').fillna(method='ffill').fillna(method='bfill')

df.info()

plt.figure(figsize=(12, 6))
plt.plot(df['Cloture'],linewidth = 1)
plt.xlabel('Date')
plt.ylabel('cloture')
plt.show()

decomposition = seasonal_decompose(df['Cloture'], model="multiplicative",period=252)

# Extraction des composantes
trend = decomposition.trend
seasonal = decomposition.seasonal
residual = decomposition.resid

plt.figure(figsize=(10, 8))

plt.subplot(411)
plt.plot(df['Cloture'], label='Originale')
plt.legend(loc='upper left')

plt.subplot(412)
plt.plot(trend, label='Tendance')
plt.legend(loc='upper left')

plt.subplot(413)
plt.plot(seasonal, label='Saisonnalité')
plt.legend(loc='upper left')

plt.subplot(414)
plt.plot(residual, label='Résidu')
plt.legend(loc='upper left')

plt.tight_layout()
plt.show()

result = adfuller(df['Cloture'], autolag='AIC')

# Affiche la statistique du test et la valeur p
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])

# Interpréter les résultats
if result[1] < 0.05:
    print('La série est stationnaire.')
else:
    print('La série est non-stationnaire.')

fig, (ax1, ax2)= plt.subplots(1,2, figsize=(12, 4))

# Tracé de la fonction d'autocorrélation (ACF)

plot_acf(df['Cloture'],lags=50, ax=ax1)
ax1.set_title('ACF')

# Tracé de la fonction d'autocorrélation partielle (PACF) pour la série différenciéé deux fois
plot_pacf(df['Cloture'],lags=50, ax=ax2)
ax2.set_title('PACF')

plt.show()

ts_diff =df['Cloture'].diff()
ts_diff.head()

ts_diff =df['Cloture'].diff().dropna()
ts_diff.head()

result = adfuller(ts_diff, autolag='AIC')

# Affiche la statistique du test et la valeur p
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])

# Interpréter les résultats
if result[1] < 0.05:
    print('La série est stationnaire.')
else:
    print('La série est non-stationnaire.')

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))

# Tracé de la série initiale et différenciée
df['Cloture'].plot(title="Série originale",color="tab:blue", ax=ax1)

ts_diff.plot(title="Série différenciée d'ordre 1", color="tab:red", ax=ax2)

plt.show()

"""#### AR(1,1,0)"""

size= int(len(df)*0.8)
train_ts = df['Cloture'].iloc[:size]
test_ts  = df['Cloture'].iloc[size:]

from pmdarima import auto_arima

model = auto_arima(train_ts, start_p=0,d=1,start_q=0,
         max_p=5,max_d=5,max_q=5)

print(model.summary())

"""### Comparaison entre arima(3,1,0) et arima(1,1,0)"""

model1 = ARIMA(train_ts, order = (1,1,0))
model1_fit = model1.fit()
print(model1_fit.summary())

model2 = ARIMA(train_ts, order = (4,1,2))
model2_fit = model2.fit()
print(model2_fit.summary())

model.plot_diagnostics(figsize=(10, 8), lags=30);

# Prédiction one-step-ahead : à chaque pas on réentraîne avec la vraie valeur
history = list(train_ts)
predictions = []

for i in range(len(test_ts)):
    model_temp = ARIMA(history, order=(2,1,1)).fit()
    yhat = model_temp.forecast(steps=1)[0]
    predictions.append(yhat)
    history.append(test_ts.iloc[i])

prediction_walk = pd.Series(predictions, index=test_ts.index)

# Graphique
plt.figure(figsize=(14, 6))
plt.plot(train_ts.index, train_ts, label='Train data', color='steelblue', linewidth=0.8)
plt.plot(test_ts.index, test_ts, label='Test data (réel)', color='orange', linewidth=1.2)
plt.plot(prediction_walk.index, prediction_walk, label='Prédiction ARIMA(2,1,1) one-step',
         color='green', linewidth=1.2, linestyle='--')
plt.title('Prédiction one-step-ahead - ARIMA(2,1,1)', fontsize=14)
plt.xlabel('Date')
plt.ylabel('Prix de clôture (TND)')
plt.legend()
plt.tight_layout()
plt.show()

# Métriques
rmse = np.sqrt(mean_squared_error(test_ts, prediction_walk))
mae  = mean_absolute_error(test_ts, prediction_walk)
mape = np.mean(np.abs((test_ts.values - prediction_walk.values) / test_ts.values)) * 100
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")
print(f"MAPE : {mape:.2f}%")

ts_diff_S = ts_diff.diff(5).dropna()

result = adfuller(ts_diff_S, autolag='AIC')

# Affiche la statistique du test et la valeur p
print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])

# Interpréter les résultats
if result[1] < 0.05:
    print('La série est stationnaire.')
else:
    print('La série est non-stationnaire.')

model = auto_arima(train_ts,
        start_p=3,d=1,start_q=0,
         max_p=3,max_d=1,max_q=0,
        start_P=0,D=1, start_Q=0,
        max_P=5,max_D=5,max_Q=5,
        m=5,seasonal=True)

print(model.summary())

model_S = ARIMA(train_ts, order = (3,1,0), seasonal_order=(5,1,1,5))
model_S_fit = model_S.fit()
print(model_S_fit.summary())

model_S_fit.plot_diagnostics(figsize=(10, 8), lags=30);

lb_test = acorr_ljungbox(model_S_fit.resid, lags=30, return_df = True)

# Afficher les résultats du test
if lb_test.iloc[0, 1] < 0.05:
    print("Le test de Ljung-Box montre que les résidus ne sont pas indépendants.")
    print("P-value :", lb_test.iloc[0, 1])
else:
    print("Le test de Ljung-Box montre que les résidus sont indépendants.")
    print("P-value :", lb_test.iloc[0, 1])

from statsmodels.tsa.statespace.sarimax import SARIMAX
import warnings
warnings.filterwarnings("ignore")

# ── Fit unique sur train ──
model_fit = SARIMAX(
    train_ts,
    order=(3, 1, 0),
    seasonal_order=(5, 1, 1, 5),
    enforce_stationarity=False,
    enforce_invertibility=False
).fit(disp=False)

# ── One-step-ahead via apply ──
predictions = []
history = train_ts.copy()

for i in range(len(test_ts)):
    res = model_fit.apply(history)
    yhat = res.forecast(steps=1).iloc[0]  # ← .iloc[0] au lieu de [0]
    predictions.append(yhat)
    new_obs = test_ts.iloc[[i]]
    history = pd.concat([history, new_obs])

prediction_walk = pd.Series(predictions, index=test_ts.index)

# ── Graphique ──
plt.figure(figsize=(14, 6))
plt.plot(train_ts.index, train_ts, label='Train data', color='steelblue', linewidth=0.8)
plt.plot(test_ts.index, test_ts, label='Test data (réel)', color='orange', linewidth=1.2)
plt.plot(prediction_walk.index, prediction_walk,
         label='Prédiction SARIMA(1,1,0)(5,1,1)[5] one-step',
         color='green', linewidth=1.2, linestyle='--')
plt.title('Prédiction one-step-ahead - SARIMA(1,1,0)(5,1,1)[5]', fontsize=14)
plt.xlabel('Date')
plt.ylabel('Prix de clôture (TND)')
plt.legend()
plt.tight_layout()
plt.show()

# ── Métriques ──
rmse = np.sqrt(mean_squared_error(test_ts, prediction_walk))
mae  = mean_absolute_error(test_ts, prediction_walk)
mape = np.mean(np.abs((test_ts.values - prediction_walk.values) / test_ts.values)) * 100
print(f"RMSE : {rmse:.4f}")
print(f"MAE  : {mae:.4f}")
print(f"MAPE : {mape:.2f}%")